---
title: Useful sources
author: ''
date: '2021-10-01'
slug: []
categories:
  - random
tags:
  - R
  - random
---
#### R+
* [R for Data Science](https://r4ds.had.co.nz/index.html) 
by _Hadley Wickham_ and _Garrett Grolemund_.  
* [R Markdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/) 
by _Yihui Xie, Christophe Dervieux,_ and _Emily Riederer_.  
* [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/) 
by _Yihui Xie, J. J. Allaire,_ and _Garrett Grolemund_.  
* [R Packages](https://r-pkgs.org) 
by _Hadley Wickham_ and _Jenny Bryan_.  
* [blogdown: Creating Websites with R Markdown](https://bookdown.org/yihui/blogdown/) 
by _Yihui Xie, Amber Thomas,_ and _Alison Presmanes Hill_.  
* [The tidyverse style guide](https://style.tidyverse.org/index.html).  
* [Happy Git with R](https://happygitwithr.com) 
by _Jenny Bryan_.  

#### Write thesis in R Markdown
* A great tutorial [here](https://ourcodingclub.github.io/tutorials/rmarkdown-dissertation/)  
* Another great [tutorial](https://rosannavanhespen.nl/thesis-in-rmarkdown/) 
by _Rosanna van Hespen_  

#### Bayesian data analysis
* [Doing Bayesian Data Analysis](https://sites.google.com/site/doingbayesiandataanalysis/) 
by _John Kruschke_.  
	+ [(Re)Doing Bayesain Data Analysis](https://rpruim.github.io/Kruschke-Notes/) by _R Pruim_.  
	+ [Doing Bayesian Data Analysis in brms and the tidyverse](https://bookdown.org/content/3686/) by _A Solomon Kurz_.  
* [Statistical Rethinking](http://xcelab.net/rm/statistical-rethinking/) by _Richard McElreath_.  
	+ [Statistical rethinking with brms, ggplot2, and the tidyverse](https://bookdown.org/content/4857/) by _A Solomon Kurz_.  
	
#### Data visualization
* [Fundamentals of Data Visualization](https://clauswilke.com/dataviz/) 
by _Claus O. Wilke_.  
* [R Graphics Cookbook](https://r-graphics.org) 
by _Winston Chang_.  

#### Other
* [Coding Club](https://ourcodingclub.github.io)  
* [Reproducible Research Tutorial Series](https://riffomonas.org/reproducible_research/) 
and [YouTube channel](https://www.youtube.com/c/RiffomonasProject) 
by _Riffomonas_.   

