baseurl: https://example.org/
title: Le Huynh's blog
theme: hugo-creative-portfolio-theme
languageCode: en-us
disqusShortname: ''
googleAnalytics: ''
params:
  copyright: '&copy;2021 Le Huynh'
  description: R notes to myself
  email: you@yoursite.com
  navlinks:
    - home: yes
      name: Home
      url: post/
    - name: About
      url: about/
  sidebarAbout:
    - Personal notes about R and 1001 interesting things on my coding journey 
  social:
#    email: trucly.lehuynh@gmail.com
#    facebook: full page or profile url in facebook
    github: https://github.com/le-huynh
#    gitlab: full profile url in gitlab
#    googleplus: full profile url in googleplus
#    instagram: full profile url in instagram
#    linkedin: https://www.linkedin.com/in/le-huynh-truc-ly
#    stackoverflow: full profile url in stackoverflow
#    twitter: full profile url in twitter
#    whatsapp: wa.me service link
#    youtube: full profile url in youtube
  style: default

