baseurl: "https://lehuynh.rbind.io/"
title: Le-Huynh Truc-Ly
theme: hugo-creative-portfolio-theme
languageCode: en-us
disqusShortname: ''
googleAnalytics: 'G-VKCP9ZH816'
params:
  style: "default"
  copyright: '&copy;2021-2025 Le-Huynh Truc-Ly'
  description: Le-Huynh Truc-Ly
  email: you@yoursite.com
  navlinks:
    - home: yes
      name: About Me
      url: about/
    - name: Projects
      url: project/
    - name: Blog
      url: blog/
    - name: Repositories
      url: github-repository/
    - name: CV
      url: Le-Huynh_Truc-Ly_CV.pdf

  sidebarAbout:
    - An R enthusiast driven by environmental concern and a love for nature  
  social:
    email: trucly.lehuynh@gmail.com
#    facebook: full page or profile url in facebook
    github: https://github.com/le-huynh
#    gitlab: full profile url in gitlab
#    googleplus: full profile url in googleplus
#    instagram: full profile url in instagram
    linkedin: https://www.linkedin.com/in/le-huynh-truc-ly
#    stackoverflow: full profile url in stackoverflow
#    twitter: full profile url in twitter
#    whatsapp: wa.me service link
#    youtube: full profile url in youtube


markup:
  goldmark:
    renderer:
      unsafe: true
