---
# title: "publications"
toc: true
---
## Peer-reviewed articles
- **Le‑Huynh, T.‑L.**, Novicoff, W. M., DeGuzman, P. B., Davis, R. E. (2026). Assessing the Importance of Spatial Scale in Climate-Health Models: the Effect of Temperature on Emergency Department Visits in Richmond, Virginia. [*GeoHealth*, 10, e2026GH001852](https://doi.org/10.1029/2026gh001852){target=_blank}.

- Nguyen, V. T. H., **Le‑Huynh, T.‑L.**, Gadola, S., Nguyen, Q., Walters, G., Owuor, M. A (2025). Local-Global Linkages in Biodiversity Governance: The Regime Complex of the Convention on Biological Diversity Agenda for Nature Pledges. [*Environmental Science & Policy*, 173(November), 104246](https://doi.org/10.1016/j.envsci.2025.104246){target=_blank}.

- Saenchan, S., Shimizu, K., Iwami, N., Angalika, M. W. S., Maseda, H., Minh, N. B., Vu, H. V., **Le‑Huynh, T.‑L.**, Itayama, T. (2025). Effects of pH and ultrasonication for decomposition of Microcystis formed colony in a bloom sample from a reservoir. [*Desalination and Water Treatment*, 322, 101203](https://doi.org/10.1016/j.dwt.2025.101203){target=_blank}. 

- Huynh, V. V., Nguyen, M. B., Somsri, S., **Le‑Huynh, T.‑L.**, Ueyama, T., Shirayanagi, S., Itayama, T. (2023). Investigation of performance in MBR operated with low DO for low C/N ratio wastewater. [*Water, Air, & Soil Pollution*. 235(540)](https://doi.org/10.1007/s11270-024-07347-3){target=_blank}.

- **Le‑Huynh, T.‑L.**, Itayama, T., Mitsunaga, K., Angalika, M., Suzuki, S. (2022). Application of hurdle Poisson model to predict the abundance of toxic cyanobacteria Microcystis in reservoirs. [*Maejo International Journal of Energy and Environmental Communication*, 4(3), 47–51](https://doi.org/10.54279/mijeec.v4i3.247529){target=_blank}.

- **Le‑Huynh, T.‑L.**, Iwami, N., Whangchai, N., Gutierrez, R., Shimizu, K., Itayama, T. (2022). Statistical analysis of the effects of environmental factors and fish species on class‑sorted phytoplankton composition in aquaculture ponds in northern Thailand. [*Maejo International Journal of Energy and Environmental Communication*, 4(3), 32–38](https://doi.org/10.54279/mijeec.v4i3.247635){target=_blank}.

- Angalika, M. W. S., Suzuki, S., **Le‑Huynh, T.‑L.**, Itayama, T., Tanaka, W. (2022). Assessing nutrient budget of ungauged catchment using intermittent water quality markers. [*Maejo International Journal of Energy and Environmental Communication*, 4(3), 1–10](https://doi.org/10.54279/mijeec.v4i3.247534){target=_blank}.

- Hoang, T. T. T., Ichinose, K., Morimoto, S., Furukawa, K., **Le-Huynh, T.-L.**, Kawakami, A. (2022). Measurement of anti‑suprabasin antibodies, multiple cytokines and chemokines as potential predictive biomarkers for neuropsychiatric systemic lupus erythematosus. [*Clinical Immunology*, 237(March), 1–8](https://doi.org/10.1016/j.clim.2022.108980){target=_blank}.

## Reproducible research code
- **Le‑Huynh, T.‑L.**, Novicoff, W. M., DeGuzman, P. B., Davis, R. E. (2026). Reproducible code for "Assessing the Importance of Spatial Scale in Climate-Health Models: the Effect of Temperature on Emergency Department Visits in Richmond, Virginia" (Version v1.0.0) [Computer software]. Zenodo. [https://doi.org/10.5281/zenodo.20076108](https://doi.org/10.5281/zenodo.20076108){target=_blank}

- Nguyen, V. T. H., **Le‑Huynh, T.‑L.**. (2026). Reproducible code for "Local-global linkages in biodiversity governance: The regime complex of the convention on biological diversity agenda for nature pledges" (Version v1.0.0) [Computer software]. Zenodo. [https://doi.org/10.5281/zenodo.20495877](https://doi.org/10.5281/zenodo.20495877){target=_blank}

- **Le-Huynh, T.-L.**. (2023). Bayesian predictive model for toxic cyanobacteria occurrence from eutrophication and climate data (Version v1.0.0) [Computer software]. Zenodo. [https://doi.org/10.5281/zenodo.20472023](https://doi.org/10.5281/zenodo.20472023){target=_blank}

- **Le-Huynh, T.-L.**. (2023). Reproducible code for "Measurement of anti-suprabasin antibodies, multiple cytokines and chemokines as potential predictive biomarkers for neuropsychiatric systemic lupus erythematosus" (Version v1.0.0) [Computer software]. GitHub. [https://github.com/le-huynh/2022_Hoang_SBSN_ClinImmunol](https://github.com/le-huynh/2022_Hoang_SBSN_ClinImmunol){target=_blank}

## R packages
- [**chva.extras**](https://le-huynh.github.io/chva.extras/){target=_blank}: Supplementary tools for climate and health research in Virginia, supporting large‑scale data manipulation, analysis, and visualization. **Le-Huynh, T.-L.**, Davis, R. E., Novicoff, W. M., DeGuzman, P. B. (2025) (Version v0.1.0) [Computer software]. Zenodo. [https://doi.org/10.5281/zenodo.14910967](https://doi.org/10.5281/zenodo.14910967){target=_blank}

- [**omics4drug**](https://yen-kim.github.io/omics4drug/){target=_blank}: R toolkit for mass spectrometry-based proteomics and phosphoproteomics analysis, supporting quality control, normalization, pathway enrichment, and drug-target prediction. Nguyen, T.-K. Y., **Le-Huynh, T.-L.** (2025) (Version v0.1.0) [Computer software]. Zenodo. [https://doi.org/10.5281/zenodo.17117624](https://doi.org/10.5281/zenodo.17117624){target=_blank}

- **cellviability**: R toolkit for analysis of cell-based drug screening experiments, including dose-response modelling, IC50
estimation, and drug combination synergy analysis. Nguyen, Y. T.-K., **Le-Huynh, T.-L.**, Theilgaard-Monch, K. (2026) (Version v0.1.3) [Computer software]. Zenodo. [https://doi.org/10.5281/zenodo.21820265](https://doi.org/10.5281/zenodo.21820265){target=_blank}

- [**lehuynh**](https://le-huynh.github.io/lehuynh/){target=_blank}: Personal R package, including functions and templates for exploratory analysis, Bayesian modeling, and crafting scientific manuscripts. **Le-Huynh, T.-L.**. (2023) (Version v0.1.1) [Computer software]. Zenodo. [https://doi.org/10.5281/zenodo.11522849](https://doi.org/10.5281/zenodo.11522849){target=_blank} | [CRAN](https://cran.r-project.org/web/packages/lehuynh/index.html){target=_blank}

